version: "1.0"
sudo: required
services:
  - docker

before_install:
  - docker build -t zinalacina/docker-react-aws -f Dockerfile.dev .

script:
  - docker run zinalacina/docker-react-aws npm run test -- --coverage